#!/usr/bin/env python3
"""Regenerate ``Formula/makkuro.rb`` resource blocks from PyPI.

Fetches the sdist URL and sha256 for each Python dependency, then rewrites
the ``resource "<name>" do ... end`` blocks between the markers
``# resources:begin`` / ``# resources:end`` in ``Formula/makkuro.rb``.

The release workflow also patches the top-level ``url`` / ``sha256`` for the
tagged source tarball. This script only touches PyPI resources.

Usage:
    python scripts/update_formula.py           # update in place
    python scripts/update_formula.py --check   # fail if the formula is stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FORMULA = ROOT / "Formula" / "makkuro.rb"

# (package_name, version)
# All resources are pinned to specific versions so CI is deterministic.
# Direct deps match the pyproject.toml runtime pins. Bump transitives with:
#     python scripts/update_formula.py --refresh-transitives
RESOURCES: list[tuple[str, str]] = [
    ("starlette", "0.49.1"),
    ("uvicorn", "0.32.1"),
    ("httpx", "0.28.1"),
    ("anyio", "4.13.0"),
    ("idna", "3.11"),
    ("sniffio", "1.3.1"),
    ("click", "8.3.2"),
    ("h11", "0.16.0"),
    ("certifi", "2026.2.25"),
    ("httpcore", "1.0.9"),
]

BEGIN = "  # resources:begin (generated by scripts/update_formula.py)"
END = "  # resources:end"


def fetch_sdist(name: str, version: str) -> tuple[str, str, str]:
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=15) as r:  # noqa: S310
        data = json.loads(r.read())
    resolved = data["info"]["version"]
    for f in data["urls"]:
        if f.get("packagetype") == "sdist":
            return resolved, f["url"], f["digests"]["sha256"]
    raise RuntimeError(f"no sdist available for {name}=={resolved}")


def render_block(name: str, url: str, sha256: str) -> str:
    return (
        f'  resource "{name}" do\n'
        f'    url "{url}"\n'
        f'    sha256 "{sha256}"\n'
        f"  end"
    )


def build_block() -> str:
    parts: list[str] = [BEGIN]
    for name, version in RESOURCES:
        _v, url, sha = fetch_sdist(name, version)
        parts.append(render_block(name, url, sha))
    parts.append(END)
    return "\n\n".join(parts[:1] + parts[1:-1]) + "\n\n" + END


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit non-zero if formula is stale")
    args = parser.parse_args()

    text = FORMULA.read_text(encoding="utf-8")
    pattern = re.compile(
        rf"^{re.escape(BEGIN)}$.*?^{re.escape(END)}$",
        re.DOTALL | re.MULTILINE,
    )
    new_block = build_block()
    if not pattern.search(text):
        print(
            f"error: {FORMULA} does not contain '{BEGIN}'/'{END}' markers",
            file=sys.stderr,
        )
        return 2
    updated = pattern.sub(new_block, text)

    if args.check:
        if updated != text:
            print("Formula resources are out of date. Run scripts/update_formula.py.")
            return 1
        print("Formula resources are up to date.")
        return 0

    if updated == text:
        print("Formula resources unchanged.")
    else:
        FORMULA.write_text(updated, encoding="utf-8")
        print(f"Updated {FORMULA}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
