"""Self-integrity verification (SC-7).

At runtime the proxy can verify that the installed package has not been
tampered with since the release manifest was published. The manifest is a
small TOML blob shipped in the wheel under
``makkuro/_integrity/manifest.toml`` listing the SHA-256 of every .py
source file the release was built from.

The manifest is generated by the release workflow; for dev installs it
either doesn't exist (in which case :func:`verify` reports that) or was
generated locally for testing (:func:`generate_manifest`).
"""

from __future__ import annotations

import hashlib
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

_PACKAGE_ROOT = Path(__file__).parent
_MANIFEST_REL_PATH = Path("_integrity") / "manifest.toml"


@dataclass
class VerificationReport:
    ok: bool
    checked: int = 0
    missing: list[str] = field(default_factory=list)
    modified: list[str] = field(default_factory=list)
    unexpected: list[str] = field(default_factory=list)
    manifest_present: bool = True

    def summary(self) -> str:
        if not self.manifest_present:
            return "no manifest shipped (dev install?) — run with --no-integrity-check"
        if self.ok:
            return f"ok: {self.checked} file(s) match manifest"
        return (
            f"FAIL: checked={self.checked} "
            f"missing={len(self.missing)} "
            f"modified={len(self.modified)} "
            f"unexpected={len(self.unexpected)}"
        )


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(65536), b""):
            h.update(block)
    return h.hexdigest()


def _walk_py_files(root: Path) -> list[Path]:
    return sorted(p for p in root.rglob("*.py") if p.is_file())


def generate_manifest(root: Path | None = None) -> dict[str, str]:
    """Hash every ``.py`` under the package and return a {relpath: sha256} map."""
    root = root if root is not None else _PACKAGE_ROOT
    out: dict[str, str] = {}
    for p in _walk_py_files(root):
        rel = p.relative_to(root).as_posix()
        out[rel] = _sha256(p)
    return out


def load_manifest(root: Path | None = None) -> dict[str, str] | None:
    root = root if root is not None else _PACKAGE_ROOT
    manifest_path = root / _MANIFEST_REL_PATH
    if not manifest_path.exists():
        return None
    data = tomllib.loads(manifest_path.read_text(encoding="utf-8"))
    files = data.get("files") or {}
    if not isinstance(files, dict):
        return None
    return {str(k): str(v) for k, v in files.items() if isinstance(v, str)}


def verify(root: Path | None = None) -> VerificationReport:
    """Compare every installed ``.py`` against the shipped manifest."""
    root = root if root is not None else _PACKAGE_ROOT
    manifest = load_manifest(root)
    if manifest is None:
        return VerificationReport(ok=False, manifest_present=False)

    report = VerificationReport(ok=True)
    on_disk = {p.relative_to(root).as_posix(): p for p in _walk_py_files(root)}

    # Skip the manifest helpers themselves — rehashing them while they're
    # being read could produce false positives in edge cases.
    skip = {_MANIFEST_REL_PATH.as_posix(), "integrity.py"}

    for rel, expected in manifest.items():
        if rel in skip:
            continue
        path = root / rel
        if not path.exists():
            report.missing.append(rel)
            report.ok = False
            continue
        report.checked += 1
        actual = _sha256(path)
        if actual != expected:
            report.modified.append(rel)
            report.ok = False

    for rel in on_disk:
        if rel in skip:
            continue
        if rel not in manifest:
            report.unexpected.append(rel)
            report.ok = False

    return report
